# # # n = 56
# # # print (bin(n))
# # # # #Question 2
# # # print(7*2)
# # # #Question 3 
# # # print("Study with python")
# # # #Question 4
# # print("12 x 4 = ", 12*4) #Option 1
# # print(f"12 x 4 = {12*4}") #Option 2
# # #Question 10 
# # print("*")
# # print("**")
# # print("***")
# # print("****")   
# # print("*****")
# # print("******")
# # print("*******")
# # print("********")
# # print("*********")
# # print("**********")
# # print("***********")
# # print("************")
# # print("*************")

# for i in range (1,13):
#     print(" * "*i)

# #Option 3

# n = 12
# for i in range (1,n +1):
#     for j in range (i ,i+1):
#         print(" * " * i )
#     print()